"""add_index_nome_orgao

Revision ID: 245026308d91
Revises: 387bb497cced
Create Date: 2026-03-19 12:28:10.185377

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "245026308d91"
down_revision: Union[str, None] = "387bb497cced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_remuneration_collected_nome_orgao"),
        "remuneration_collected",
        ["nome_orgao"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_remuneration_collected_nome_orgao"), table_name="remuneration_collected")
    # ### end Alembic commands ###
