"""initial_schema

Revision ID: 387bb497cced
Revises: None
Create Date: 2026-03-19 12:14:38.343147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387bb497cced'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_annual',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ano_exercicio', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_meses_processados', sa.Integer(), nullable=False),
    sa.Column('total_paginas_consumidas', sa.Integer(), nullable=False),
    sa.Column('total_registros_coletados', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_annual_ano_exercicio'), 'execution_annual', ['ano_exercicio'], unique=False)
    op.create_table('execution_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paginas_consumidas', sa.Integer(), nullable=False),
    sa.Column('registros_coletados', sa.Integer(), nullable=False),
    sa.Column('total_pages_informado', sa.Integer(), nullable=True),
    sa.Column('total_elements_informado', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_annual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_monthly_execution_id'), 'execution_monthly', ['execution_id'], unique=False)
    op.create_table('remuneration_collected',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('monthly_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('ano_exercicio', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=2), nullable=False),
    sa.Column('codigo_identificacao', sa.String(length=50), nullable=False),
    sa.Column('codigo_matricula', sa.String(length=50), nullable=False),
    sa.Column('cpf_servidor', sa.String(length=20), nullable=True),
    sa.Column('nome_servidor', sa.String(length=255), nullable=False),
    sa.Column('codigo_orgao', sa.String(length=50), nullable=True),
    sa.Column('nome_orgao', sa.Text(), nullable=True),
    sa.Column('situacao_funcional', sa.String(length=100), nullable=True),
    sa.Column('situacao_funcional_detalhada', sa.Text(), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('funcao', sa.String(length=255), nullable=True),
    sa.Column('valor_remuneracao_basica', sa.Float(), nullable=False),
    sa.Column('valor_beneficios', sa.Float(), nullable=False),
    sa.Column('valor_funcoes', sa.Float(), nullable=False),
    sa.Column('valor_comissao_conselheiro', sa.Float(), nullable=False),
    sa.Column('valor_hora_extra', sa.Float(), nullable=False),
    sa.Column('valor_verbas_eventuais', sa.Float(), nullable=False),
    sa.Column('valor_verbas_judiciais', sa.Float(), nullable=False),
    sa.Column('valor_receitas_meses_anteriores', sa.Float(), nullable=False),
    sa.Column('valor_reposicao_descontos_maior', sa.Float(), nullable=False),
    sa.Column('valor_licenca_premio', sa.Float(), nullable=False),
    sa.Column('valor_imposto_renda', sa.Float(), nullable=False),
    sa.Column('valor_seguridade_social', sa.Float(), nullable=False),
    sa.Column('valor_redutor_teto', sa.Float(), nullable=False),
    sa.Column('valor_descontos_meses_anteriores', sa.Float(), nullable=False),
    sa.Column('valor_reposicao_pagamento_maior', sa.Float(), nullable=False),
    sa.Column('valor_expurgo', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_annual.id'], ),
    sa.ForeignKeyConstraint(['monthly_execution_id'], ['execution_monthly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remuneration_collected_ano_exercicio'), 'remuneration_collected', ['ano_exercicio'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_codigo_identificacao'), 'remuneration_collected', ['codigo_identificacao'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_codigo_matricula'), 'remuneration_collected', ['codigo_matricula'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_codigo_orgao'), 'remuneration_collected', ['codigo_orgao'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_execution_id'), 'remuneration_collected', ['execution_id'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_mes_referencia'), 'remuneration_collected', ['mes_referencia'], unique=False)
    op.create_index(op.f('ix_remuneration_collected_monthly_execution_id'), 'remuneration_collected', ['monthly_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remuneration_collected_monthly_execution_id'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_mes_referencia'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_execution_id'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_codigo_orgao'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_codigo_matricula'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_codigo_identificacao'), table_name='remuneration_collected')
    op.drop_index(op.f('ix_remuneration_collected_ano_exercicio'), table_name='remuneration_collected')
    op.drop_table('remuneration_collected')
    op.drop_index(op.f('ix_execution_monthly_execution_id'), table_name='execution_monthly')
    op.drop_table('execution_monthly')
    op.drop_index(op.f('ix_execution_annual_ano_exercicio'), table_name='execution_annual')
    op.drop_table('execution_annual')
    # ### end Alembic commands ###
